import { CiSaveDown2 } from "react-icons/ci";
import { CiEdit } from "react-icons/ci";
import { MdDelete } from "react-icons/md";

export const AssessmentData = [
	{
		id: 1,
		exam: [
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		id: 20,
		exam: [
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		id: 2,
		exam: [
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	
];
