import { CiSaveDown2 } from "react-icons/ci";
import { CiEdit } from "react-icons/ci";
import { MdDelete } from "react-icons/md";
import Switch from "@mui/material/Switch";

export const AssessmentData = [
	{
		id: "assessment",
		exam: [
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		exam: [
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},

	{
		name: "department",

		department: [
			{
				number: 1,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 2,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 3,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 4,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 5,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 6,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		name: "designations",
		designation: [
			{
				number: 1,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 2,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 3,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 4,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 5,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 6,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		name: "positions",
		positions: [
			{
				id: 1,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
			{
				id: 2,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: true,
				status: "Vacant",
				employeeassign: "Assign Empployee",
			},
			{
				id: 3,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
			{
				id: 4,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
			{
				id: 5,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
			{
				id: 6,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
		],
	},
	{
		name: "employee",
		employee: [
			{
				id: 1,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 2,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 3,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 4,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 5,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 6,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
		],
	},
	{
		name: "group",

		group: [
			{
				id: 1,
				name: "Group1",
				tag: "Education",
				members: "View",

				active: true,
			},
			{
				id: 2,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: false,
			},
			{
				id: 3,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: true,
			},
			{
				id: 4,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: false,
			},
			{
				id: 5,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: true,
			},
			{
				id: 6,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: false,
			},
		],
	},
	{
		name: "Users",
		users: [
			{
				id: 1,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
			},
			{
				id: 2,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
			},
			{
				id: 3,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
			},
			{
				id: 4,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
			},
			{
				id: 5,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
			},
			{
				id: 6,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
			},
		],
	},
	{
		name: "approve",
		approves: [
			{
				id: 1,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Green",
				removecolor: "Gray",
			},
			{
				id: 2,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Gray",
				removecolor: "Red",
			},
			{
				id: 3,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Green",
				removecolor: "Gray",
			},
			{
				id: 4,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Gray",
				removecolor: "Red",
			},
			{
				id: 5,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Green",
				removecolor: "Gray",
			},
		],
	},
	{
		name: "invitation",
		invitation: [
			{
				id: 1,
				code: "INVITE1043",
				maxinvitation: 13,
				expiry: "24-12-31",
				edit: CiEdit,
				active: true,
			},
			{
				id: 2,
				code: "INVITE1043",
				maxinvitation: 10,
				expiry: "24-12-31",
				edit: CiEdit,
				active: false,
			},
			{
				id: 3,
				code: "INVITE1043",
				maxinvitation: "Unlimited",
				expiry: "24-12-31",
				edit: CiEdit,
				active: true,
			},
			{
				id: 4,
				code: "INVITE1043",
				maxinvitation: 4,
				expiry: "24-12-31",
				edit: CiEdit,
				active: false,
			},
			{
				id: 5,
				code: "INVITE1043",
				maxinvitation: 7,
				expiry: "24-12-31",
				edit: CiEdit,
				active: true,
			},
		],
	},
];
