import { CiSaveDown2 } from "react-icons/ci";
import { CiEdit } from "react-icons/ci";
import { MdDelete } from "react-icons/md";
import Switch from "@mui/material/Switch";
import { IoCheckmark } from "react-icons/io5";
import { FaExpandAlt } from "react-icons/fa";
import { MdOutlineRadioButtonChecked } from "react-icons/md";

export const AssessmentData = [
	{
		name: "assessments",
		exam: [
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		exam: [
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				title: "Exam Prep Guides",
				tag: "Tag 1",
				tag2: "Tag 2",
				group: "Group 1",
				esay: "Esay",
				set: "Set A",
				version: "Version 2",
				pending: "Pending",
				save: CiSaveDown2,
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},

	{
		name: "department",

		department: [
			{
				number: 1,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 2,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 3,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 4,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 5,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 6,
				data: "Research And Development",
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		name: "designations",
		designation: [
			{
				number: 1,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 2,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 3,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 4,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 5,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				number: 6,
				data: "Research And Development",
				secondData: "Assistant Professor",
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		name: "positions",
		positions: [
			{
				id: 1,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
			{
				id: 2,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: true,
				status: "Vacant",
				employeeassign: "Assign Empployee",
			},
			{
				id: 3,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
			{
				id: 4,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
			{
				id: 5,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
			{
				id: 6,
				name: "Software Engineer",
				appication: "Web Applications",
				employee: "001, User 1",
				role: "Developer",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
			},
		],
	},
	{
		name: "employee",
		employee: [
			{
				id: 1,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 2,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 3,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 4,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 5,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: true,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
			{
				id: 6,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",
				designatoin: "Software Engineer",
				department: "Department 1",
				active: false,
				status: "Assigned",
				employeeassign: "Assign Empployee",
				edit: CiEdit,
			},
		],
	},
	{
		name: "group",
		group: [
			{
				id: 1,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: true,
			},
			{
				id: 2,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: false,
			},
			{
				id: 3,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: true,
			},
			{
				id: 4,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: false,
			},
			{
				id: 5,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: true,
			},
			{
				id: 6,
				name: "Group1",
				tag: "Education",
				members: "View",
				active: false,
			},
		],
	},
	{
		name: "Users",
		users: [
			{
				id: 1,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
			},
			{
				id: 2,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
			},
			{
				id: 3,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
			},
			{
				id: 4,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
			},
			{
				id: 5,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
			},
			{
				id: 6,
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
			},
		],
	},
	{
		name: "approve",
		approves: [
			{
				id: 1,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Green",
				removecolor: "Gray",
			},
			{
				id: 2,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Gray",
				removecolor: "Red",
			},
			{
				id: 3,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Green",
				removecolor: "Gray",
			},
			{
				id: 4,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: false,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Gray",
				removecolor: "Red",
			},
			{
				id: 5,
				group: "Group 1",
				invitationcode: "INV123",
				name: "User 1",
				email: "user1234@gmail.com",
				phoneno: "+91 8987653459",
				active: true,
				accpect: "Accpect",
				remove: "Remove",
				accpectcolor: "Green",
				removecolor: "Gray",
			},
		],
	},
	{
		name: "invitation",
		invitation: [
			{
				id: 1,
				code: "INVITE1043",
				maxinvitation: 13,
				expiry: "24-12-31",
				edit: CiEdit,
				active: true,
			},
			{
				id: 2,
				code: "INVITE1043",
				maxinvitation: 10,
				expiry: "24-12-31",
				edit: CiEdit,
				active: false,
			},
			{
				id: 3,
				code: "INVITE1043",
				maxinvitation: "Unlimited",
				expiry: "24-12-31",
				edit: CiEdit,
				active: true,
			},
			{
				id: 4,
				code: "INVITE1043",
				maxinvitation: 4,
				expiry: "24-12-31",
				edit: CiEdit,
				active: false,
			},
			{
				id: 5,
				code: "INVITE1043",
				maxinvitation: 7,
				expiry: "24-12-31",
				edit: CiEdit,
				active: true,
			},
		],
	},
	{
		name: "version",
		version: [
			{
				id: 1,
				version: 1.2,
				setcorrection: "Explicit",
				status: "Draft",
				edit: CiEdit,
				publish: "Publish",
				switch: "Switch",
			},
			{
				id: 2,
				version: 1.2,
				setcorrection: "Automatic",
				status: "Draft",
				edit: CiEdit,
				publish: "Darft",
				switch: "Switch",
			},
			{
				id: 3,
				version: 1.2,
				setcorrection: "Automatic",
				status: "Draft",
				edit: CiEdit,
				publish: "Publish",
				switch: "Switch",
			},
			{
				id: 4,
				version: 1.2,
				setcorrection: "Automatic",
				status: "Draft",
				edit: CiEdit,
				publish: "Draft",
				switch: "Switch",
			},
			{
				id: 5,
				version: 1.2,
				setcorrection: "Automatic",
				status: "Draft",
				edit: CiEdit,
				publish: "Publish",
				switch: "Switch",
			},
			{
				id: 6,
				version: 1.5,
				setcorrection: "Automatic",
				status: "Draft",
				edit: CiEdit,
				publish: "Draft",
				switch: "Switch",
			},
		],
	},
	{
		name: "section",
		section: [
			{
				id: 1,
				order: 1,
				section: "Hindi",
				maxque: "45",
				mark: 2,
				equalmarks: "yes",
				negitivemark: "25%",
				shuffle: "No",
				status: "Active",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				id: 2,
				order: 1,
				section: "Mathematics",
				maxque: "45",
				equalmarks: "No",
				negitivemark: "50%",
				shuffle: "No",
				status: "Inactive",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				id: 3,
				order: 2,
				section: "English",
				maxque: "45",
				equalmarks: "45",
				negitivemark: "100%",
				shuffle: "No",
				status: "Inactive",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				id: 4,
				order: 4,
				section: "Science",
				maxque: "45",
				equalmarks: "45",
				negitivemark: "100%",
				shuffle: "No",
				status: "Inactive",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				id: 5,
				order: 5,
				section: "Geography",
				maxque: "45",
				equalmarks: "45",
				negitivemark: "100%",
				shuffle: "No",
				status: "Inactive",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				id: 6,
				order: 6,
				section: "Hindi",
				maxque: "45",
				equalmarks: "45",
				negitivemark: "100%",
				shuffle: "No",
				status: "Inactive",
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		name: "set",
		sets: [
			{
				id: 1,
				code: "AA-001",
				question: "45",
				reviewed: "4",
				unreviewed: 1,
				status: "Active",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				id: 2,
				code: "AA-002",
				question: "45",
				reviewed: "4",
				unreviewed: 1,
				status: "Pending",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				id: 3,
				code: "AA-003",
				question: "45",
				reviewed: "4",
				unreviewed: 1,
				status: "Not Answered",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				id: 4,
				code: "AA-004",
				question: "45",
				reviewed: "4",
				unreviewed: 1,
				status: "Active",
				edit: CiEdit,
				delete: MdDelete,
			},
			{
				id: 5,
				code: "AA-005",
				question: "45",
				reviewed: "4",
				unreviewed: 1,
				status: "Active",
				edit: CiEdit,
				delete: MdDelete,
			},
		],
	},
	{
		name: "schedule",
		schedules: [
			{
				id: 1,
				version: "1",
				timezone: "UTC Offset: UTC+ 5:30",
				from: "12-july, 8 AM",
				untill: "12-july, 12 AM",
				status: "Active",
				edit: CiEdit,
				live: "yes",
			},
			{
				id: 2,
				version: "1",
				timezone: "UTC Offset: UTC+ 5:30",
				from: "12-july, 8 AM",
				untill: "12-july, 12 AM",
				status: "Active",
				edit: CiEdit,
			},
			{
				id: 3,
				version: "1",
				timezone: "UTC Offset: UTC+ 5:30",
				from: "12-july, 8 AM",
				untill: "12-july, 12 AM",
				status: "Active",
				edit: CiEdit,
			},
			{
				id: 4,
				version: "1",
				timezone: "UTC Offset: UTC+ 5:30",
				from: "12-july, 8 AM",
				untill: "12-july, 12 AM",
				status: "Active",
				edit: CiEdit,
			},
			{
				id: 5,
				version: "1",
				timezone: "UTC Offset: UTC+ 5:30",
				from: "12-july, 8 AM",
				untill: "12-july, 12 AM",
				status: "Active",
				edit: CiEdit,
			},
		],
	},
	{
		name: "question",
		question: [
			{
				heading:
					"Calculate the circumference of a circle with a radius of 7 cm7,\text{cm}7cm (π=3.14pi = 3.14π=3.14).",
				SingleChoice: "Single Choice",
				tag: "Tag1",
				tag2: "Tag2",
				easy: "Easy",
				setA: "SetA",
				check: IoCheckmark,
				edit: CiEdit,
				delete: MdDelete,
				expand: FaExpandAlt,
				radioButton: MdOutlineRadioButtonChecked,
			},
			{
				heading:
					"Calculate the circumference of a circle with a radius of 7 cm7,\text{cm}7cm (π=3.14pi = 3.14π=3.14).",
				SingleChoice: "Single Choice",
				tag: "Tag1",
				tag2: "Tag2",
				easy: "Easy",
				setA: "SetA",
				check: IoCheckmark,
				edit: CiEdit,
				delete: MdDelete,
				expand: FaExpandAlt,
				radioButton: MdOutlineRadioButtonChecked,
			},
			{
				heading:
					"Calculate the circumference of a circle with a radius of 7 cm7,\text{cm}7cm (π=3.14pi = 3.14π=3.14).",
				SingleChoice: "Single Choice",
				tag: "Tag1",
				tag2: "Tag2",
				easy: "Easy",
				setA: "SetA",
				check: IoCheckmark,
				edit: CiEdit,
				delete: MdDelete,
				expand: FaExpandAlt,
				radioButton: MdOutlineRadioButtonChecked,
			},
			{
				heading:
					"Calculate the circumference of a circle with a radius of 7 cm7,\text{cm}7cm (π=3.14pi = 3.14π=3.14).",
				SingleChoice: "Single Choice",
				tag: "Tag1",
				tag2: "Tag2",
				easy: "Easy",
				setA: "SetA",
				check: IoCheckmark,
				edit: CiEdit,
				delete: MdDelete,
				expand: FaExpandAlt,
				radioButton: MdOutlineRadioButtonChecked,
			},
			{
				heading:
					"Calculate the circumference of a circle with a radius of 7 cm7,\text{cm}7cm (π=3.14pi = 3.14π=3.14).",
				SingleChoice: "Single Choice",
				tag: "Tag1",
				tag2: "Tag2",
				easy: "Easy",
				setA: "SetA",
				check: IoCheckmark,
				edit: CiEdit,
				delete: MdDelete,
				expand: FaExpandAlt,
				radioButton: MdOutlineRadioButtonChecked,
			},
			{
				heading:
					"Calculate the circumference of a circle with a radius of 7 cm7,\text{cm}7cm (π=3.14pi = 3.14π=3.14).",
				SingleChoice: "Single Choice",
				tag: "Tag1",
				tag2: "Tag2",
				easy: "Easy",
				setA: "SetA",
				check: IoCheckmark,
				edit: CiEdit,
				delete: MdDelete,
				expand: FaExpandAlt,
				radioButton: MdOutlineRadioButtonChecked,
			},
		],
	},
	{
		name: "Group",
		group: [
			{
				id: 1,
				name: "Group 1",
				participants: "View",
				tag: "Education",
				active: true,
			},
			{
				id: 2,
				name: "Group 2",
				participants: "View",
				tag: "Education",
				active: false,
			},
			{
				id: 3,
				name: "Group 3",
				participants: "View",
				tag: "Education",
				active: false,
			},
			{
				id: 4,
				name: "Group 4",
				participants: "View",
				tag: "Education",
				active: false,
			},
			{
				id: 5,
				name: "Group 5",
				participants: "View",
				tag: "Education",
				active: true,
			},
		],
	},
	{
		name: "individual",
		individual: [
			{
				id: 1,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",

				active: true,
			},
			{
				id: 2,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",

				active: false,
			},
			{
				id: 3,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",

				active: true,
			},
			{
				id: 4,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",

				active: false,
			},
			{
				id: 5,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",

				active: true,
			},
			{
				id: 6,
				name: "User1",
				email: "user123@gmail.com",
				phoneno: "+91 8764289075",

				active: false,
			},
		],
	},
];
